"""Seed canonical entity list — known AI companies and their aliases."""

CANONICAL_ENTITIES = {
    "OpenAI": ["openai", "open ai", "openai inc", "openai, inc.", "open ai inc", "chatgpt", "gpt-4", "dall-e", "sora", "o1"],
    "Google DeepMind": ["deepmind", "google deepmind", "deep mind", "alphabet deepmind"],
    "Anthropic": ["anthropic", "anthropic ai", "anthropic pbc", "claude"],
    "Meta AI": ["meta ai", "facebook ai", "meta platforms ai", "fair", "facebook ai research"],
    "Microsoft AI": ["microsoft ai", "ms ai", "microsoft research ai", "copilot", "github copilot"],
    "NVIDIA": ["nvidia", "nvidia ai", "nvidia corporation", "nvda"],
    "Tesla AI": ["tesla ai", "tesla autopilot", "tesla fsd"],
    "Amazon AI": ["amazon ai", "aws ai", "amazon machine learning", "bedrock", "sagemaker"],
    "Apple AI": ["apple ai", "apple intelligence", "apple machine learning"],
    "IBM Watson": ["ibm watson", "watson ai", "ibm ai", "watsonx"],
    "Cohere": ["cohere", "cohere ai", "cohere inc"],
    "Stability AI": ["stability ai", "stabilityai", "stable diffusion", "stability ai ltd"],
    "Midjourney": ["midjourney", "midjourney inc", "mj"],
    "Hugging Face": ["hugging face", "huggingface", "hf"],
    "Databricks": ["databricks", "databricks inc", "databricks ai"],
    "Palantir": ["palantir", "palantir technologies", "palantir ai"],
    "Scale AI": ["scale ai", "scaleai", "scale ai inc"],
    "C3.ai": ["c3.ai", "c3 ai", "c3 ai inc", "c3 ai enterprise"],
    "DataRobot": ["datarobot", "data robot", "datarobot inc"],
    "Figure AI": ["figure ai", "figure robotics", "figure"],
    "Inflection AI": ["inflection ai", "inflection"],
    "Character AI": ["character ai", "character.ai", "character ai inc"],
    "Perplexity AI": ["perplexity", "perplexity ai", "perplexity.ai"],
    "xAI": ["xai", "x ai", "x.ai", "xai corp"],
    "Mistral AI": ["mistral ai", "mistral", "mistral technologies"],
    "Runway": ["runway", "runway ml", "runway ai", "runway gen-2"],
    "Jasper AI": ["jasper", "jasper ai", "jasper.ai"],
    "Copy.ai": ["copy.ai", "copy ai"],
    "Grammarly": ["grammarly", "grammarly ai"],
    "Notion AI": ["notion ai", "notion"],
    "Cursor": ["cursor", "cursor ai", "cursor editor", "anysphere"],
    "Replit AI": ["replit", "replit ai", "replit inc"],
    "Vercel AI": ["vercel ai", "vercel", "v0"],
    "LangChain": ["langchain", "langchain inc", "lang chain"],
    "Pinecone": ["pinecone", "pinecone systems", "pinecone ai"],
    "Weaviate": ["weaviate", "weaviate bv"],
    "Chroma": ["chroma", "chroma db", "chroma vector"],
    "Weights & Biases": ["weights & biases", "wandb", "weights and biases"],
    "Weights and Biases": ["weights & biases", "wandb", "weights and biases"],
    "Anyscale": ["anyscale", "anyscale inc"],
    "Groq": ["groq", "groq inc", "groq ai"],
    "SambaNova": ["sambanova", "samba nova", "sambanova systems"],
    "Cerebras": ["cerebras", "cerebras systems"],
    "Baseten": ["baseten", "baseten co"],
    "Modal": ["modal", "modal labs"],
    "Replicate": ["replicate", "replicate inc"],
    "Together AI": ["together ai", "togetherai", "together ai inc"],
    "Fireworks AI": ["fireworks ai", "fireworks"],
    "DeepSeek": ["deepseek", "deep seek", "deepseek ai", "deepseek inc"],
    "Moonshot AI": ["moonshot ai", "moonshot", "kimi"],
    "01.AI": ["01.ai", "01 ai", "yi", "yi-34b"],
    "Zhipu AI": ["zhipu ai", "zhipu", "chatglm"],
    "Minimax": ["minimax", "minimax ai"],
    "Runway ML": ["runway ml", "runway", "runway ai"],
    "Adept AI": ["adept ai", "adept"],
    "Covariant": ["covariant", "covariant ai"],
    "Sanctuary AI": ["sanctuary ai", "sanctuary"],
    "1X Technologies": ["1x technologies", "1x", "1x robotics"],
    "Mistral": ["mistral", "mistral ai"],
    "Voyage AI": ["voyage ai", "voyage"],
    "Cohere For AI": ["cohere for ai", "c4ai"],
    "Zoo.dev": ["zoo.dev", "zoo"],
    "Magic AI": ["magic ai", "magic"],
    "Windsurf": ["windsurf", "codeium", "windsurf ai"],
    "Augment Code": ["augment code", "augment"],
    "Poolside AI": ["poolside ai", "poolside"],
    "Typeface AI": ["typeface ai", "typeface"],
    "Writer AI": ["writer", "writer ai", "writer inc"],
    "Glean": ["glean", "glean ai", "glean inc"],
    "Hebbia": ["hebbia", "hebbia ai"],
    "Snorkel AI": ["snorkel ai", "snorkel"],
    "Labelbox": ["labelbox", "labelbox inc"],
    "Scale AI": ["scale ai", "scaleai"],
    "Hugging Face": ["hugging face", "huggingface", "hf"],
    "Replicate": ["replicate", "replicate inc"],
    "Luma AI": ["luma ai", "luma", "luma dream machine"],
    "Runway Gen-3": ["runway gen-3", "runway"],
    "Pika Labs": ["pika", "pika labs", "pika ai"],
    "ElevenLabs": ["elevenlabs", "eleven labs", "elevenlabs inc"],
    "Deepgram": ["deepgram", "deepgram inc"],
    "AssemblyAI": ["assemblyai", "assembly ai"],
    "Weights & Biases": ["wandb", "weights & biases"],
    "Anyscale": ["anyscale", "ray", "ray serve"],
    "Modal Labs": ["modal", "modal labs", "modal.com"],
    "Bento ML": ["bento ml", "bentoml"],
    "Banana.dev": ["banana", "banana dev", "banana.dev"],
    "Banana ML": ["banana ml", "banana"],
    "Baseten": ["baseten", "baseten co"],
    "Valentine AI": ["valentine ai", "valentine"],
    "Adept": ["adept", "adept ai", "adept research"],
    "Inflection": ["inflection", "inflection ai"],
    "Cohere": ["cohere", "cohere ai"],
    "Aleph Alpha": ["aleph alpha", "aleph ai"],
    "Stability AI": ["stability ai", "stabilityai"],
    "Runway": ["runway", "runway ml"],
    "Jasper": ["jasper", "jasper ai"],
    "Copy.ai": ["copy.ai", "copy ai"],
    "Writesonic": ["writesonic", "writesonic ai"],
    "Synthesia": ["synthesia", "synthesia ai", "synthesia inc"],
    "D-ID": ["d-id", "d id", "d-id ai"],
    "HeyGen": ["heygen", "hey gen"],
    "Descript": ["descript", "descript inc"],
    "Otter.ai": ["otter.ai", "otter ai"],
    "Fireflies.ai": ["fireflies.ai", "fireflies ai"],
    "Mem.ai": ["mem.ai", "mem ai"],
    "Raycast AI": ["raycast", "raycast ai"],
    "Arc Browser": ["arc browser", "arc", "the browser company"],
    "Anthropic Claude": ["claude", "claude ai", "claude 3"],
    "Google Gemini": ["gemini", "google gemini", "bard", "google bard"],
    "Microsoft Copilot": ["copilot", "microsoft copilot", "github copilot"],
    "Amazon Q": ["amazon q", "q ai", "q developer"],
}
